In [149]:
import pandas as pd
import numpy as np

In [150]:
df = pd.read_excel(
    r"D:\DataAnalysis\NTI\Project\FinalCleaningPowerQuery.xlsx",
    sheet_name="WORKOUT_SESSION_3"
)

In [151]:
df2 = df.copy()
df2

,Session_ID,User_ID,Gym_ID,Checkin_Time,Checkout_Time,Workout_Type,Calories_Burned,Session_Duration
0,396,user_3243,gym_6,2023-03-24 15:29:00,2023-03-24 17:48:00,Cardio,1019.0,02:19:00
1,397,user_3532,gym_6,2023-03-28 19:27:00,2023-03-28 22:24:00,Yoga,295.0,02:57:00
2,398,user_3249,gym_3,2023-04-12 08:01:00,2023-04-12 09:06:00,CrossFit,912.0,01:05:00
3,399,user_1124,gym_9,2023-09-13 13:40:00,2023-09-13 15:02:00,Yoga,NaN,01:22:00
4,400,user_4729,gym_8,2023-10-04 11:40:00,2023-10-04 14:04:00,Pilates,1480.0,02:24:00
...,...,...,...,...,...,...,...,...
300328,304891,user_4289,gym_5,2023-02-20 19:22:00,2023-02-20 20:56:00,Pilates,NaN,01:34:00
300329,304892,user_4319,gym_6,2023-02-02 15:37:00,NaT,Weightlifting,1062.0,NaN
300330,304893,user_2025,gym_4,2023-07-23 09:02:00,2023-07-23 10:18:00,Pilates,1568.0,01:16:00
300331,304894,user_2889,gym_6,2023-08-15 06:18:00,2023-08-15 06:55:00,Pilates,592.0,00:37:00
300332,304895,user_3439,gym_5,2023-05-02 15:29:00,2023-05-02 16:01:00,Swimming,1345.0,00:32:00

In [152]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 300333 entries, 0 to 300332
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Session_ID        300333 non-null  int64
 1   User_ID           300333 non-null  str
 2   Gym_ID            300333 non-null  str
 3   Checkin_Time      300333 non-null  datetime64[us]
 4   Checkout_Time     294325 non-null  datetime64[us]
 5   Workout_Type      300333 non-null  str
 6   Calories_Burned   291405 non-null  float64
 7   Session_Duration  294325 non-null  object
dtypes: datetime64[us](2), float64(1), int64(1), object(1), str(3)
memory usage: 18.3+ MB

In [153]:
df2.describe(include='all')

,Session_ID,User_ID,Gym_ID,Checkin_Time,Checkout_Time,Workout_Type,Calories_Burned,Session_Duration
count,300333.000000,300333,300333,300333,294325,300333,291405.000000,294325
unique,NaN,5000,10,NaN,NaN,7,NaN,170
top,NaN,user_1099,gym_3,NaN,NaN,Weightlifting,NaN,00:47:00
freq,NaN,89,30328,NaN,NaN,50355,NaN,2075
mean,151920.435094,NaN,NaN,2023-05-24 22:30:36.968365,2023-05-25 00:18:33.982026,NaN,930.066701,NaN
min,396.000000,NaN,NaN,2023-01-01 05:35:00,2023-01-01 06:25:00,NaN,-50.000000,NaN
25%,75710.000000,NaN,NaN,2023-03-14 08:41:00,2023-03-14 10:19:00,NaN,530.000000,NaN
50%,151543.000000,NaN,NaN,2023-05-24 17:31:00,2023-05-24 19:34:00,NaN,833.000000,NaN
75%,227944.000000,NaN,NaN,2023-08-04 14:44:00,2023-08-04 16:40:00,NaN,1181.000000,NaN
max,304895.000000,NaN,NaN,2023-10-15 20:59:00,2023-10-15 23:43:00,NaN,15000.000000,NaN
std,87902.623474,NaN,NaN,NaN,NaN,NaN,889.823887,NaN

In [154]:
df2.tail()

,Session_ID,User_ID,Gym_ID,Checkin_Time,Checkout_Time,Workout_Type,Calories_Burned,Session_Duration
300328,304891,user_4289,gym_5,2023-02-20 19:22:00,2023-02-20 20:56:00,Pilates,NaN,01:34:00
300329,304892,user_4319,gym_6,2023-02-02 15:37:00,NaT,Weightlifting,1062.0,NaN
300330,304893,user_2025,gym_4,2023-07-23 09:02:00,2023-07-23 10:18:00,Pilates,1568.0,01:16:00
300331,304894,user_2889,gym_6,2023-08-15 06:18:00,2023-08-15 06:55:00,Pilates,592.0,00:37:00
300332,304895,user_3439,gym_5,2023-05-02 15:29:00,2023-05-02 16:01:00,Swimming,1345.0,00:32:00

In [155]:
df2.head()

,Session_ID,User_ID,Gym_ID,Checkin_Time,Checkout_Time,Workout_Type,Calories_Burned,Session_Duration
0,396,user_3243,gym_6,2023-03-24 15:29:00,2023-03-24 17:48:00,Cardio,1019.0,02:19:00
1,397,user_3532,gym_6,2023-03-28 19:27:00,2023-03-28 22:24:00,Yoga,295.0,02:57:00
2,398,user_3249,gym_3,2023-04-12 08:01:00,2023-04-12 09:06:00,CrossFit,912.0,01:05:00
3,399,user_1124,gym_9,2023-09-13 13:40:00,2023-09-13 15:02:00,Yoga,NaN,01:22:00
4,400,user_4729,gym_8,2023-10-04 11:40:00,2023-10-04 14:04:00,Pilates,1480.0,02:24:00

In [156]:
df2.shape

(300333, 8)

In [157]:
df2.columns.tolist()

['Session_ID',
 'User_ID',
 'Gym_ID',
 'Checkin_Time',
 'Checkout_Time',
 'Workout_Type',
 'Calories_Burned',
 'Session_Duration']

In [158]:
df2.isnull().any()

Session_ID          False
User_ID             False
Gym_ID              False
Checkin_Time        False
Checkout_Time        True
Workout_Type        False
Calories_Burned      True
Session_Duration     True
dtype: bool

In [159]:
df2.isnull().sum()

Session_ID             0
User_ID                0
Gym_ID                 0
Checkin_Time           0
Checkout_Time       6008
Workout_Type           0
Calories_Burned     8928
Session_Duration    6008
dtype: int64

Fill Nulls in (Calories_Burned) With Median

In [160]:
med =df2.Calories_Burned.median()
med

np.float64(833.0)

In [161]:
df2['Calories_Burned'] = df2.Calories_Burned.fillna(med)

In [162]:
df2.isnull().sum()

Session_ID             0
User_ID                0
Gym_ID                 0
Checkin_Time           0
Checkout_Time       6008
Workout_Type           0
Calories_Burned        0
Session_Duration    6008
dtype: int64

Outlayers

In [163]:
df2 = df2[df2['Calories_Burned'] > 0]

In [164]:
Q2 = df2.Calories_Burned.median()
Q2

np.float64(833.0)

In [165]:
q1= np.quantile(df2.Calories_Burned, 0.25)
q1

np.float64(544.0)

In [166]:
q3 = np.quantile(df2.Calories_Burned, 0.75 )
q3

np.float64(1171.0)

In [167]:
IQR = q3 - q1
IQR

np.float64(627.0)

In [168]:
l = q1- (1.5 *IQR )
l

np.float64(-396.5)

In [169]:
u = q3 + (1.5 * IQR)
u

np.float64(2111.5)

In [170]:
out = df2[(df2.Calories_Burned < l) | 
         (df2.Calories_Burned > u)]

out

,Session_ID,User_ID,Gym_ID,Checkin_Time,Checkout_Time,Workout_Type,Calories_Burned,Session_Duration
605,1001,user_2427,gym_7,2023-07-03 14:04:00,2023-07-03 16:16:00,Weightlifting,9999.0,02:12:00
658,1054,user_4484,gym_9,2023-08-08 20:09:00,2023-08-08 21:21:00,CrossFit,9999.0,01:12:00
918,1314,user_4232,gym_2,2023-08-28 10:56:00,NaT,Yoga,9999.0,NaN
1242,1638,user_2407,gym_2,2023-07-17 06:29:00,2023-07-17 09:18:00,Pilates,15000.0,02:49:00
1621,2017,user_1642,gym_7,2023-07-24 13:38:00,2023-07-24 15:57:00,Weightlifting,15000.0,02:19:00
...,...,...,...,...,...,...,...,...
299395,303932,user_691,gym_10,2023-05-18 20:50:00,2023-05-18 22:21:00,CrossFit,2114.0,01:31:00
299537,304078,user_66,gym_6,2023-04-20 07:04:00,2023-04-20 07:47:00,Swimming,9999.0,00:43:00
299600,304142,user_2378,gym_5,2023-10-05 12:31:00,2023-10-05 14:18:00,CrossFit,9999.0,01:47:00
299655,304200,user_1402,gym_1,2023-03-26 06:29:00,2023-03-26 09:08:00,Swimming,9999.0,02:39:00
300269,304832,user_3029,gym_9,2023-06-28 20:11:00,2023-06-28 22:49:00,Yoga,9999.0,02:38:00

In [171]:
df2 = df2[
    (df2['Calories_Burned'] <= u) &
    (df2['Calories_Burned'] >= l)
]

In [172]:
df2['Calories_Burned'] = df2['Calories_Burned'].astype(int)

In [173]:
df2.describe(include="all")

,Session_ID,User_ID,Gym_ID,Checkin_Time,Checkout_Time,Workout_Type,Calories_Burned,Session_Duration
count,297168.000000,297168,297168,297168,291218,297168,297168.000000,291218
unique,NaN,5000,10,NaN,NaN,7,NaN,170
top,NaN,user_1099,gym_3,NaN,NaN,Weightlifting,NaN,00:47:00
freq,NaN,89,30021,NaN,NaN,49812,NaN,2056
mean,151905.236381,NaN,NaN,2023-05-24 22:19:47.649814,2023-05-25 00:10:07.548778,NaN,883.761620,NaN
min,396.000000,NaN,NaN,2023-01-01 05:35:00,2023-01-01 06:25:00,NaN,150.000000,NaN
25%,75700.750000,NaN,NaN,2023-03-14 08:22:45,2023-03-14 09:58:30,NaN,543.000000,NaN
50%,151504.500000,NaN,NaN,2023-05-24 17:23:30,2023-05-24 19:29:00,NaN,833.000000,NaN
75%,227938.250000,NaN,NaN,2023-08-04 14:45:15,2023-08-04 16:45:00,NaN,1165.000000,NaN
max,304895.000000,NaN,NaN,2023-10-15 20:59:00,2023-10-15 23:43:00,NaN,2111.000000,NaN
std,87899.328650,NaN,NaN,NaN,NaN,NaN,425.463041,NaN

Fill Nulls in CheckOut Time

In [174]:
df2.isnull().sum()

Session_ID             0
User_ID                0
Gym_ID                 0
Checkin_Time           0
Checkout_Time       5950
Workout_Type           0
Calories_Burned        0
Session_Duration    5950
dtype: int64

In [175]:
sd= df2.Checkout_Time - df2.Checkin_Time

In [176]:
M_sd = sd.mean()
M_sd

Timedelta('0 days 01:43:49.124435')

In [177]:
df2.Checkout_Time = df2.Checkout_Time.fillna(df2.Checkin_Time + M_sd )

In [178]:
df2.Checkout_Time.isnull().sum()

np.int64(0)

In [179]:
print(df2['Checkin_Time'].dtype)
print(df2['Checkout_Time'].dtype)

datetime64[us]
datetime64[us]

In [193]:
df2['Session_Duration'] = (
    (df2['Checkout_Time'] - df2['Checkin_Time'])
    .dt.total_seconds() / 60
).round().astype(int)

In [194]:
df2.Session_Duration

0         139
1         177
2          65
3          82
4         144
         ...
300328     94
300329    104
300330     76
300331     37
300332     32
Name: Session_Duration, Length: 297168, dtype: int64

In [195]:
invalid_time = df2[ df2['Checkout_Time'] < df2['Checkin_Time'] ] 
print(invalid_time.shape)

(0, 8)

In [196]:
df2.isnull().sum()

Session_ID          0
User_ID             0
Gym_ID              0
Checkin_Time        0
Checkout_Time       0
Workout_Type        0
Calories_Burned     0
Session_Duration    0
dtype: int64

In [197]:
df2.duplicated().sum()

np.int64(0)

In [199]:
print(df2['Workout_Type'].unique())

<StringArray>
['Cardio', 'Yoga', 'CrossFit', 'Pilates', 'Swimming', 'Weightlifting',
 'Cardo']
Length: 7, dtype: str

In [200]:
df2['Workout_Type']  = df2["Workout_Type"].replace(
    "Cardo", "Cardio"
)

In [202]:
df2['Workout_Type'].unique()

<StringArray>
['Cardio', 'Yoga', 'CrossFit', 'Pilates', 'Swimming', 'Weightlifting']
Length: 6, dtype: str

In [203]:
df2 = df2.reset_index(drop=True)

In [205]:
print(df2.isnull().sum())
print(df2.shape)

Session_ID          0
User_ID             0
Gym_ID              0
Checkin_Time        0
Checkout_Time       0
Workout_Type        0
Calories_Burned     0
Session_Duration    0
dtype: int64
(297168, 8)

In [206]:
print(df2.columns.tolist())
print(df2.nunique())

['Session_ID', 'User_ID', 'Gym_ID', 'Checkin_Time', 'Checkout_Time', 'Workout_Type', 'Calories_Burned', 'Session_Duration']
Session_ID          297168
User_ID               5000
Gym_ID                  10
Checkin_Time        176836
Checkout_Time       186179
Workout_Type             6
Calories_Burned       1962
Session_Duration       170
dtype: int64

In [207]:
df2.duplicated(subset=['User_ID', 'Gym_ID', 'Checkin_Time', 
                        'Checkout_Time', 'Workout_Type', 
                        'Calories_Burned']).sum()

np.int64(169)

In [209]:
dup = df2[df2.duplicated(
    subset=['User_ID', 'Gym_ID', 'Checkin_Time', 
            'Checkout_Time', 'Workout_Type', 'Calories_Burned'], 
    keep=False
)].sort_values('User_ID')

dup

,Session_ID,User_ID,Gym_ID,Checkin_Time,Checkout_Time,Workout_Type,Calories_Burned,Session_Duration
260694,267053,user_1000,gym_3,2023-09-01 11:39:00,2023-09-01 14:17:00.000000,Swimming,638,158
53002,54081,user_1000,gym_3,2023-09-01 11:39:00,2023-09-01 14:17:00.000000,Swimming,638,158
200504,204891,user_1007,gym_9,2023-02-20 13:37:00,2023-02-20 15:20:49.124435,Pilates,833,104
156246,159341,user_1007,gym_9,2023-02-20 13:37:00,2023-02-20 15:20:49.124435,Pilates,833,104
30454,31216,user_1009,gym_9,2023-06-01 11:38:00,2023-06-01 12:28:00.000000,Weightlifting,1050,50
...,...,...,...,...,...,...,...,...
202179,206619,user_970,gym_4,2023-02-10 15:43:00,2023-02-10 16:23:00.000000,Cardio,765,40
19801,20433,user_974,gym_10,2023-04-21 13:39:00,2023-04-21 14:17:00.000000,Yoga,337,38
38640,39513,user_974,gym_10,2023-04-21 13:39:00,2023-04-21 14:17:00.000000,Yoga,337,38
133789,136368,user_994,gym_3,2023-01-08 20:53:00,2023-01-08 21:33:00.000000,Weightlifting,915,40
160835,164053,user_994,gym_3,2023-01-08 20:53:00,2023-01-08 21:33:00.000000,Weightlifting,915,40

In [210]:
df2 = df2.drop_duplicates(
    subset=['User_ID', 'Gym_ID', 'Checkin_Time', 
            'Checkout_Time', 'Workout_Type', 'Calories_Burned'],
    keep='first'
)

print(df2.shape)

(296999, 8)

In [211]:
df2 = df2.reset_index(drop=True)

In [213]:
print(df2.isnull().sum())
print(df2.shape)

Session_ID          0
User_ID             0
Gym_ID              0
Checkin_Time        0
Checkout_Time       0
Workout_Type        0
Calories_Burned     0
Session_Duration    0
dtype: int64
(296999, 8)

In [214]:
df2.to_excel(
    r"D:\DataAnalysis\NTI\Project\Final_Python_Cleaning.xlsx",
    index=False
)